config/routes.rb
Rails.application.routes.draw do

  resources :reservations

  root 'reservations#new'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservations_priv)
    @reservation.save
    redirect_to url_for(:controller => :reservations, :action => :index)
  end
  
  def show
    @reservation = Reservation.find(params[:id])
  end
  
  def index
    @reservation = Reservation.all
  end


  private
  def reservations_priv
    params.require(:reservation).permit(:customer, :phone_number, :number_of_people, :reservation_datetime)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/index.html.erb
<script type="text/javascript">
       
            function redirect_method() {
               window.location="/reservations/new";
            }
         
      </script>
  
  



<table border="1" style="width:600px; height:200px;">
<tr>

<th>customer</th>
<th>phone no</th>
<th>total people</th>
<th>reservation datetime</th>
</tr>
<% @reservation.each do |res| %>
<tr>
<td><%= res.customer %></td>
<td><%= res.phone_number %></td>
<td> <%= res.number_of_people %></td>
<td>
 <%= res.reservation_datetime %></td>
</tr>

<%end%>
</table>
<br>


<input type="button" value="Goto New Reservation" onclick="redirect_method();" />

app/views/reservations/new.html.erb
<div style = "background-color: lightgrey; margin: 0; height: 620px; ">




<h2> Enter Customer Reservation Details : </h2>
<hr>
<%= form_for @reservation do |f|%> <br/>
 <table style="width: 97.7%;margin-left: 20px;margin-top: 20px" >
          <tr style="height: 30px">
          	<td>
              <%= f.label "Customer Name", :style => "margin-right:50px;font-weight:bold;font-family: Book Antiqua;color:#303030"%>
            </td>
            <td>
              <%= f.text_field :customer,:size=>15, :style=>"color:#303030" %>
            </td>
          </tr>
          <tr>
           <td><br/>
              <%= f.label "Phone number",:style => "margin-right:35px; margin-top: 10px;font-weight:bold;font-family: Book Antiqua;color:#303030"  %>
            </td>
            <td>
              <%= f.telephone_field :phone_number ,:size=>15, :style=>"color:#303030" %>
            </td>
          </tr>

          <tr>
           <td><br/>
              <%= f.label "Total People",:style => "margin-right:35px; margin-top: 10px;font-weight:bold;font-family: Book Antiqua;color:#303030"  %>
            </td>
            <td>
              <%= f.text_field :number_of_people ,:size=>15, :style=>"color:#303030" %>
            </td>
          </tr>
          <tr>
             <td><br/>
              <%= f.label "Reservation DateTime",:style => "margin-right:35px; margin-top: 10px;font-weight:bold;font-family: Book Antiqua;color:#303030"  %>
            </td>
            <td>
              <%= f.datetime_select :reservation_datetime ,:size=>15, :style=>"color:#303030" %>
            </td>
          </tr>
         
        
            <tr>
             <td><br/>
              <%= f.label " ",:style => "margin-right:35px; margin-top: 10px;font-weight:bold;font-family: Book Antiqua;color:#303030"  %>
            </td>
            <td>
              <%= f.submit :size=>15, :style=>"color:#303030" %>
            </td>
          </tr>
        

        </table>


  
<% end %>
<%= button_to "View Reservations ", reservations_path, method: :get %>
</div>